"""Export the local NetPulse database into ``cloud/config.json`` for GitHub Actions.

The Actions runner has no access to your SQLite database, so the device list and
client chat ids have to live in a small committed file.

Run this whenever you add / edit a device or a group, then push:

    .venv\\Scripts\\python.exe scripts\\export_cloud_config.py
    (then push cloud/config.json)

The bot token is NEVER written here - it lives in a GitHub Actions secret.
"""
from __future__ import annotations

import ipaddress
import json
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB = ROOT / "netpulse.db"
OUT = ROOT / "cloud" / "config.json"


def is_private_host(host: str) -> bool:
    """True for RFC1918 / loopback / link-local addresses.

    A GitHub Actions runner sits on the public internet, so these can never be
    reached from there - including them would just produce permanent false
    DOWN alerts.
    """
    h = (host or "").strip().strip("[]")
    if not h:
        return False
    try:
        ip = ipaddress.ip_address(h)
    except ValueError:
        return h.lower() in ("localhost",) or h.lower().endswith(".local")
    return ip.is_private or ip.is_loopback or ip.is_link_local or ip.is_reserved


def main() -> int:
    if not DB.exists():
        print(f"!! database not found: {DB}")
        return 1

    conn = sqlite3.connect(DB)
    conn.row_factory = sqlite3.Row

    groups: dict[str, str] = {}
    for row in conn.execute("SELECT name, telegram_chat_id, enabled FROM alert_groups ORDER BY name"):
        if row["enabled"] and row["telegram_chat_id"]:
            groups[row["name"]] = str(row["telegram_chat_id"])

    default_chat = ""
    row = conn.execute("SELECT value FROM app_settings WHERE key = 'telegram_chat_id'").fetchone()
    if row and row["value"]:
        default_chat = str(row["value"])

    devices = []
    skipped_private: list[str] = []
    for dev in conn.execute(
        "SELECT id, name, host, enabled, timeout_seconds, alert_group_id, notify FROM devices ORDER BY name"
    ):
        if not dev["enabled"]:
            continue
        if is_private_host(dev["host"]):
            skipped_private.append(f"{dev['name']} ({dev['host']})")
            continue
        gname = "default"
        if dev["alert_group_id"]:
            g = conn.execute(
                "SELECT name FROM alert_groups WHERE id = ?", (dev["alert_group_id"],)
            ).fetchone()
            if g:
                gname = g["name"]

        checks = []
        for c in conn.execute(
            "SELECT type, params, enabled FROM checks WHERE device_id = ? AND enabled = 1 ORDER BY id",
            (dev["id"],),
        ):
            ctype = str(c["type"])
            if ctype == "snmp":
                # SNMP is not available from a cloud runner without a tunnel
                continue
            try:
                params = json.loads(c["params"] or "{}")
            except json.JSONDecodeError:
                params = {}
            checks.append({"type": ctype, "params": params})
        if not checks:
            continue

        devices.append(
            {
                "name": dev["name"],
                "host": dev["host"],
                "alert_group": gname,
                "timeout_seconds": dev["timeout_seconds"] or 5,
                "checks": checks,
            }
        )

    conn.close()

    config = {
        "_comment": "Generated by scripts/export_cloud_config.py - do not edit by hand.",
        "default_chat_id": default_chat,
        "groups": groups,
        "renotify_minutes": 30,
        "digest_minutes": 60,
        "latency_threshold_ms": 150,
        # GitHub runners block ICMP, so a failed ping is retried over TCP.
        "ping_fallback_tcp": True,
        "devices": devices,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(config, indent=2, ensure_ascii=False), encoding="utf-8")

    print(f"wrote {OUT}")
    print(f"  groups : {', '.join(f'{k}={v}' for k, v in groups.items()) or '(none)'}")
    print(f"  default: {default_chat or '(not set)'}")
    print(f"  devices: {len(devices)}")
    for d in devices:
        kinds = "+".join(c["type"] for c in d["checks"])
        print(f"    {d['name']:26} {d['host']:20} [{kinds}] -> {d['alert_group']}")
    if skipped_private:
        print()
        print(f"  skipped {len(skipped_private)} private host(s) - unreachable from GitHub:")
        for s in skipped_private:
            print(f"    {s}")
        print("    (these still work in the local dashboard; only the cloud job skips them)")
    print()
    print("next: git add cloud/config.json && git commit && git push")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
